import img1 from './TechnologyImages/Angular.png'
import img2 from './TechnologyImages/react.png'
import img3 from './TechnologyImages/Redux.png'
import img4 from './TechnologyImages/Bootstrap.png'
import img5 from './TechnologyImages/Node.png'
import img6 from './TechnologyImages/Python.png'
import img7 from './TechnologyImages/Azure.png'
import img8 from './TechnologyImages/Codeigniter.png'
import img9 from './TechnologyImages/Csharp.png'
import img10 from './TechnologyImages/Mysql.png'
import img11 from './TechnologyImages/Flutter.png'
import img12 from './TechnologyImages/php.png'
import img13 from './TechnologyImages/Vb.webp'
import img14 from './TechnologyImages/SharePoint.png'

export const images = [{ "img": img1 }, { "img": img2 }, { "img": img3 }, { "img": img4 }, { "img": img5 }, { "img": img6 }, { "img": img7 }, { "img": img8 }, { "img": img9 }, { "img": img10 }, { "img": img11 }, { "img": img12 }, { "img": img13 }, { "img": img14 }]